### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by ZiMo-code** [oyjcodes/tour#4]
感谢大佬，但我这边部署后，出现图片不显示的原因，希望大佬能抽空解答
![image](https://user-images.githubusercontent.com/63234041/112167127-2eb49100-8c2b-11eb-8cf5-56aa178a7d08.png)

**Comment by ZiMo-code** [comment]
我已发现问题，请问作者能否上传该项目的图片

**Comment by ZiMo-code** [comment]
感谢作者的代码，所有问题已经排除

**Comment by tt990120** [comment]
能否分享一下图片

**Comment by tt990120** [comment]
> 感谢作者的代码，所有问题已经排除

是找到该项目的图片了吗 能否分享一下图片 谢谢

**Comment by ZiMo-code** [comment]
> > 感谢作者的代码，所有问题已经排除
> 
> 是找到该项目的图片了吗 能否分享一下图片 谢谢

**Comment by ZiMo-code** [comment]
> > 感谢作者的代码，所有问题已经排除
> 
> 是找到该项目的图片了吗 能否分享一下图片 谢谢

平台首页的图片都是要自己插入的，数据库只存放图片的地址

**Comment by superXiaoai** [comment]
请问能加个联系方式吗？请教下怎么配置的，我导入不成功
